[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
chain_id = 10143

[rpc_endpoints]
monad = "${MONAD_RPC_URL}"
